version: "3.4"

services:
  tag-manager-api-web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - COMPOSER_AUTH=${COMPOSER_AUTH}
    container_name: tag-manager-api-web
    entrypoint: apache2-foreground
    env_file: .env
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: 1
    ports:
      - "8100:80"
    volumes:
      - .:/var/www/html:delegated
